[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/api/slack-paystub"
  to   = "/.netlify/functions/slack-paystub"
  status = 200

[[redirects]]
  from = "/api/admin-set-password"
  to   = "/.netlify/functions/admin-set-password"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
