-- 20261006_sales_rep_full_rate.sql — re-runnable. Paste into the Supabase SQL editor.
-- Sales Rep commission (per Isaac, Oct 6 2026): FULL commission on every
-- commissionable service type, HALF on add-ons (ticket items; the half lives in
-- adminRules.addonPay.d2d_share). This reloads the service-type list from
-- 20260623 (it was empty in production, so the calculator classified nothing)
-- and sets the Sales Rep bundle multiplier to 1. 'pest' and 'bundle' now pay
-- the same rate; one-time services, installs, initials and internal types stay
-- excluded. repRates, manual, published, payscales and the other rule blocks
-- are preserved.

insert into public.app_settings (key, value)
values (
  'commission_config',
  jsonb_build_object(
    'serviceCategories', $json${
  "Carpenter Bee 12": "bundle",
  "Carpenter Bee 4": "bundle",
  "Carpenter Bee 6": "bundle",
  "Carpenter Bee Mole 6": "bundle",
  "Commercial Hotel Service": "bundle",
  "Exclusion": "exclude",
  "German Roach 12": "bundle",
  "German Roach 4": "bundle",
  "German Roach 6": "bundle",
  "German Roach Initial": "exclude",
  "German Roach Mole 4": "bundle",
  "German Roach Package": "bundle",
  "German Roach Rodent 4": "bundle",
  "GreenSky Sentricon Install": "exclude",
  "GreenSky Sentricon North Carolina": "bundle",
  "GreenSky Sentricon South Carolina": "bundle",
  "Interior Flea 12": "bundle",
  "Interior Flea 4": "bundle",
  "Interior Flea 6": "bundle",
  "Interior Flea Initial": "exclude",
  "Interior Flea Mosquito 6 Seasonal": "bundle",
  "Meeting Day": "exclude",
  "Mole 12": "bundle",
  "Mole 4": "bundle",
  "Mole 6": "bundle",
  "Mole Initial": "exclude",
  "Mole Mosquito 4": "bundle",
  "Mole Mosquito 6": "bundle",
  "Mole Mosquito 6 Seasonal": "bundle",
  "Mole Mosquito Seasonal 6": "bundle",
  "Mole Mosquito Snake 6": "bundle",
  "Mole Pest 4": "bundle",
  "Mole Pest 6": "bundle",
  "Mole Rodent 4": "bundle",
  "Mole Rodent 6": "bundle",
  "Mole Snake 4": "bundle",
  "Mole Snake 6": "bundle",
  "Mosquito 12": "bundle",
  "Mosquito 4": "bundle",
  "Mosquito 6": "bundle",
  "Mosquito 8 Seasonal": "bundle",
  "Mosquito Bi-Monthly Seasonal": "bundle",
  "Mosquito Initial": "exclude",
  "Mosquito Rodent 4": "bundle",
  "Mosquito Rodent 6": "bundle",
  "Mosquito Rodent 6 Seasonal": "bundle",
  "Mosquito Rodent Snake 6 Seasonal": "bundle",
  "Mosquito Snake 4": "bundle",
  "One Time Fire Ant": "exclude",
  "One Time German Roach": "exclude",
  "One Time Interior Flea": "exclude",
  "One Time Mosquito": "exclude",
  "One Time Pest Control": "exclude",
  "One Time Rodent": "exclude",
  "One Time Termite Inspection": "exclude",
  "One Time Vehicle Infestation": "exclude",
  "Pest 12": "pest",
  "Pest 3": "bundle",
  "Pest 4": "pest",
  "Pest 4 - Spanish": "pest",
  "Pest 6": "pest",
  "Pest 6 - Spanish": "pest",
  "Pest Carpenter Bee 4": "bundle",
  "Pest Carpenter Bee 6": "bundle",
  "Pest Carpenter Bee German Roach 6": "bundle",
  "Pest Carpenter Bee Mole 4": "bundle",
  "Pest Carpenter Bee Mole 6": "bundle",
  "Pest Carpenter Bee Mole Mosquito 6": "bundle",
  "Pest Carpenter Bee Mole Mosquito 6 Seasonal": "bundle",
  "Pest Carpenter Bee Mole Mosquito Snake 6 Seasonal": "bundle",
  "Pest Carpenter Bee Mole Rodent 4": "bundle",
  "Pest Carpenter Bee Mole Rodent 6": "bundle",
  "Pest Carpenter Bee Mosquito 4 Seasonal": "bundle",
  "Pest Carpenter Bee Mosquito 6": "bundle",
  "Pest Carpenter Bee Mosquito 6 Seasonal": "bundle",
  "Pest Carpenter Bee Rodent 4": "bundle",
  "Pest Carpenter Bee Rodent 6": "bundle",
  "Pest Carpenter Bee Rodent Snake 4": "bundle",
  "Pest Control Bi-Monthly": "bundle",
  "Pest Control Initial": "exclude",
  "Pest Control Quarterly": "bundle",
  "Pest German Roach 12": "bundle",
  "Pest German Roach 4": "bundle",
  "Pest German Roach 6": "bundle",
  "Pest German Roach Initial": "exclude",
  "Pest German Roach Interior 4": "bundle",
  "Pest German Roach Mole 4": "bundle",
  "Pest German Roach Mole 6": "bundle",
  "Pest German Roach Mole Mosquito 6": "bundle",
  "Pest German Roach Mole Mosquito Snake 6": "bundle",
  "Pest German Roach Mole Rodent 4": "bundle",
  "Pest German Roach Mole Rodent 6": "bundle",
  "Pest German Roach Mole Snake Rodent 4": "bundle",
  "Pest German Roach Mosquito 4": "bundle",
  "Pest German Roach Mosquito 4 Seasonal": "bundle",
  "Pest German Roach Mosquito 6": "bundle",
  "Pest German Roach Mosquito 6 Seasonal": "bundle",
  "Pest German Roach Rodent 12": "bundle",
  "Pest German Roach Rodent 4": "bundle",
  "Pest German Roach Rodent 6": "bundle",
  "Pest German Roach Rodent Snake 4": "bundle",
  "Pest German Roach Rodent Snake 6": "bundle",
  "Pest German Roach Snake 4": "bundle",
  "Pest German Roach Snake 6": "bundle",
  "Pest Interior 4": "bundle",
  "Pest Interior 6": "bundle",
  "Pest Interior Flea 4": "bundle",
  "Pest Interior Flea 6": "bundle",
  "Pest Interior Flea Mole 4": "bundle",
  "Pest Interior Flea Mosquito 4": "bundle",
  "Pest Interior Flea Mosquito 4 Seasonal": "bundle",
  "Pest Interior Flea Rodent 6": "bundle",
  "Pest Interior German Roach 4": "bundle",
  "Pest Interior German Roach Rodent 4": "bundle",
  "Pest Mole 12": "bundle",
  "Pest Mole 4": "bundle",
  "Pest Mole 6": "bundle",
  "Pest Mole Initial": "exclude",
  "Pest Mole Mosquito 4": "bundle",
  "Pest Mole Mosquito 4 Seasonal": "bundle",
  "Pest Mole Mosquito 6": "bundle",
  "Pest Mole Mosquito 6 Seasonal": "bundle",
  "Pest Mole Mosquito Rodent 6": "bundle",
  "Pest Mole Mosquito Snake 4": "bundle",
  "Pest Mole Mosquito Snake 6": "bundle",
  "Pest Mole Mosquito Snake 6 Seasonal": "bundle",
  "Pest Mole Rodent 4": "bundle",
  "Pest Mole Rodent 6": "bundle",
  "Pest Mole Rodent Snake 6": "bundle",
  "Pest Mole Snake 4": "bundle",
  "Pest Mole Snake 6": "bundle",
  "Pest Mole Snake Rodent 4": "bundle",
  "Pest Mosquito 12": "bundle",
  "Pest Mosquito 3 Seasonal": "bundle",
  "Pest Mosquito 4": "bundle",
  "Pest Mosquito 4 - Spanish": "bundle",
  "Pest Mosquito 4 Seasonal": "bundle",
  "Pest Mosquito 6": "bundle",
  "Pest Mosquito 6 - Spanish": "bundle",
  "Pest Mosquito 6 Seasonal": "bundle",
  "Pest Mosquito 6 Seasonal - Spanish": "bundle",
  "Pest Mosquito Carpenter Bee 4": "bundle",
  "Pest Mosquito Initial": "exclude",
  "Pest Mosquito Rodent 6": "bundle",
  "Pest Mosquito Snake 4": "bundle",
  "Pest Mosquito Snake 4 Seasonal": "bundle",
  "Pest Mosquito Snake 6": "bundle",
  "Pest Mosquito Snake 6 Seasonal": "bundle",
  "Pest Rodent 12": "bundle",
  "Pest Rodent 3": "bundle",
  "Pest Rodent 4": "bundle",
  "Pest Rodent 6": "bundle",
  "Pest Rodent Mole 4": "bundle",
  "Pest Rodent Snake 4": "bundle",
  "Pest Rodent Snake 6": "bundle",
  "Pest Snake 12": "bundle",
  "Pest Snake 4": "bundle",
  "Pest Snake 6": "bundle",
  "Quarterly Service": "bundle",
  "RIDD Package 12": "bundle",
  "RIDD Package 4": "bundle",
  "RIDD Package 4 - Spanish": "bundle",
  "RIDD Package 4 Seasonal": "bundle",
  "RIDD Package 6": "bundle",
  "RIDD Package 6 - Spanish": "bundle",
  "RIDD Package 6 Seasonal": "bundle",
  "RIDD Package Carpenter Bee 12": "bundle",
  "RIDD Package Carpenter Bee 4": "bundle",
  "RIDD Package Carpenter Bee 6": "bundle",
  "RIDD Package Carpenter Bee 6 Seasonal": "bundle",
  "RIDD Package Carpenter Bee German Roach 4": "bundle",
  "RIDD Package Carpenter Bee Mole 4": "bundle",
  "RIDD Package Carpenter Bee Mole 6": "bundle",
  "RIDD Package Carpenter Bee Mole 6 Seasonal": "bundle",
  "RIDD Package Carpenter Bee Snake 12": "bundle",
  "RIDD Package Carpenter Bee Snake 6 Seasonal": "bundle",
  "RIDD Package German Roach 12": "bundle",
  "RIDD Package German Roach 4": "bundle",
  "RIDD Package German Roach 4 Seasonal": "bundle",
  "RIDD Package German Roach 6": "bundle",
  "RIDD Package German Roach 6 Seasonal": "bundle",
  "RIDD Package German Roach Carpenter Bee 6": "bundle",
  "RIDD Package German Roach Interior Flea 4": "bundle",
  "RIDD Package German Roach Interior Flea 6": "bundle",
  "RIDD Package German Roach Mole 4": "bundle",
  "RIDD Package German Roach Mole 6": "bundle",
  "RIDD Package German Roach Mole 6 Seasonal": "bundle",
  "RIDD Package German Roach Snake 12": "bundle",
  "RIDD Package German Roach Snake 4": "bundle",
  "RIDD Package German Roach Snake 6": "bundle",
  "RIDD Package German Roach Snake 6 Seasonal": "bundle",
  "RIDD Package Interior Flea 4": "bundle",
  "RIDD Package Interior Flea 6": "bundle",
  "RIDD Package Interior Flea 6 Seasonal": "bundle",
  "RIDD Package Interior Flea Mole 6": "bundle",
  "RIDD Package Interior Flea Mole 6 Seasonal": "bundle",
  "RIDD Package Interior Flea Snake 6 Seasonal": "bundle",
  "RIDD Package Mole 12": "bundle",
  "RIDD Package Mole 4": "bundle",
  "RIDD Package Mole 6": "bundle",
  "RIDD Package Mole 6 Seasonal": "bundle",
  "RIDD Package Mole Snake 12": "bundle",
  "RIDD Package Mole Snake 4": "bundle",
  "RIDD Package Mole Snake 6": "bundle",
  "RIDD Package Mole Snake 6 Seasonal": "bundle",
  "RIDD Package Snake 12": "bundle",
  "RIDD Package Snake 4": "bundle",
  "RIDD Package Snake 4 Seasonal": "bundle",
  "RIDD Package Snake 6": "bundle",
  "RIDD Package Snake 6 Seasonal": "bundle",
  "RIDD Package Snake Initial": "exclude",
  "Rodent 12": "bundle",
  "Rodent 4": "bundle",
  "Rodent 6": "bundle",
  "Rodent Initial": "exclude",
  "Rodent Snake 4": "bundle",
  "Seasonal Mosquito Treatment": "bundle",
  "Sentricon Florida - Repair & Retreat": "bundle",
  "Sentricon Florida - Retreat": "bundle",
  "Sentricon Georgia - Repair & Retreat": "bundle",
  "Sentricon Georgia - Retreat": "bundle",
  "Sentricon Install": "exclude",
  "Sentricon Install South Carolina": "exclude",
  "Sentricon Michigan - Retreat": "bundle",
  "Sentricon Monitoring SC": "bundle",
  "Sentricon North Carolina - Repair & Retreat": "bundle",
  "Sentricon North Carolina - Retreat": "bundle",
  "Sentricon South Carolina - Repair & Retreat": "bundle",
  "Sentricon South Carolina - Retreat": "bundle",
  "Sentricon Utah - Retreat": "bundle",
  "Sentricon Virginia - Repair & Retreat": "bundle",
  "Sentricon Virginia - Retreat": "bundle",
  "Sentricon Virginia Beach - Retreat": "bundle",
  "Snake 12": "bundle",
  "Snake 4": "bundle",
  "Snake 6": "bundle",
  "Solo Seasonal Mosquito": "bundle",
  "Termite Repair": "exclude"
}$json$::jsonb,
    'typeRules', jsonb_build_object('Sales Rep', jsonb_build_object('bundleMult', to_jsonb(1::numeric)))
  )
)
on conflict (key) do update set value =
  app_settings.value
  || jsonb_build_object('serviceCategories', $json${
  "Carpenter Bee 12": "bundle",
  "Carpenter Bee 4": "bundle",
  "Carpenter Bee 6": "bundle",
  "Carpenter Bee Mole 6": "bundle",
  "Commercial Hotel Service": "bundle",
  "Exclusion": "exclude",
  "German Roach 12": "bundle",
  "German Roach 4": "bundle",
  "German Roach 6": "bundle",
  "German Roach Initial": "exclude",
  "German Roach Mole 4": "bundle",
  "German Roach Package": "bundle",
  "German Roach Rodent 4": "bundle",
  "GreenSky Sentricon Install": "exclude",
  "GreenSky Sentricon North Carolina": "bundle",
  "GreenSky Sentricon South Carolina": "bundle",
  "Interior Flea 12": "bundle",
  "Interior Flea 4": "bundle",
  "Interior Flea 6": "bundle",
  "Interior Flea Initial": "exclude",
  "Interior Flea Mosquito 6 Seasonal": "bundle",
  "Meeting Day": "exclude",
  "Mole 12": "bundle",
  "Mole 4": "bundle",
  "Mole 6": "bundle",
  "Mole Initial": "exclude",
  "Mole Mosquito 4": "bundle",
  "Mole Mosquito 6": "bundle",
  "Mole Mosquito 6 Seasonal": "bundle",
  "Mole Mosquito Seasonal 6": "bundle",
  "Mole Mosquito Snake 6": "bundle",
  "Mole Pest 4": "bundle",
  "Mole Pest 6": "bundle",
  "Mole Rodent 4": "bundle",
  "Mole Rodent 6": "bundle",
  "Mole Snake 4": "bundle",
  "Mole Snake 6": "bundle",
  "Mosquito 12": "bundle",
  "Mosquito 4": "bundle",
  "Mosquito 6": "bundle",
  "Mosquito 8 Seasonal": "bundle",
  "Mosquito Bi-Monthly Seasonal": "bundle",
  "Mosquito Initial": "exclude",
  "Mosquito Rodent 4": "bundle",
  "Mosquito Rodent 6": "bundle",
  "Mosquito Rodent 6 Seasonal": "bundle",
  "Mosquito Rodent Snake 6 Seasonal": "bundle",
  "Mosquito Snake 4": "bundle",
  "One Time Fire Ant": "exclude",
  "One Time German Roach": "exclude",
  "One Time Interior Flea": "exclude",
  "One Time Mosquito": "exclude",
  "One Time Pest Control": "exclude",
  "One Time Rodent": "exclude",
  "One Time Termite Inspection": "exclude",
  "One Time Vehicle Infestation": "exclude",
  "Pest 12": "pest",
  "Pest 3": "bundle",
  "Pest 4": "pest",
  "Pest 4 - Spanish": "pest",
  "Pest 6": "pest",
  "Pest 6 - Spanish": "pest",
  "Pest Carpenter Bee 4": "bundle",
  "Pest Carpenter Bee 6": "bundle",
  "Pest Carpenter Bee German Roach 6": "bundle",
  "Pest Carpenter Bee Mole 4": "bundle",
  "Pest Carpenter Bee Mole 6": "bundle",
  "Pest Carpenter Bee Mole Mosquito 6": "bundle",
  "Pest Carpenter Bee Mole Mosquito 6 Seasonal": "bundle",
  "Pest Carpenter Bee Mole Mosquito Snake 6 Seasonal": "bundle",
  "Pest Carpenter Bee Mole Rodent 4": "bundle",
  "Pest Carpenter Bee Mole Rodent 6": "bundle",
  "Pest Carpenter Bee Mosquito 4 Seasonal": "bundle",
  "Pest Carpenter Bee Mosquito 6": "bundle",
  "Pest Carpenter Bee Mosquito 6 Seasonal": "bundle",
  "Pest Carpenter Bee Rodent 4": "bundle",
  "Pest Carpenter Bee Rodent 6": "bundle",
  "Pest Carpenter Bee Rodent Snake 4": "bundle",
  "Pest Control Bi-Monthly": "bundle",
  "Pest Control Initial": "exclude",
  "Pest Control Quarterly": "bundle",
  "Pest German Roach 12": "bundle",
  "Pest German Roach 4": "bundle",
  "Pest German Roach 6": "bundle",
  "Pest German Roach Initial": "exclude",
  "Pest German Roach Interior 4": "bundle",
  "Pest German Roach Mole 4": "bundle",
  "Pest German Roach Mole 6": "bundle",
  "Pest German Roach Mole Mosquito 6": "bundle",
  "Pest German Roach Mole Mosquito Snake 6": "bundle",
  "Pest German Roach Mole Rodent 4": "bundle",
  "Pest German Roach Mole Rodent 6": "bundle",
  "Pest German Roach Mole Snake Rodent 4": "bundle",
  "Pest German Roach Mosquito 4": "bundle",
  "Pest German Roach Mosquito 4 Seasonal": "bundle",
  "Pest German Roach Mosquito 6": "bundle",
  "Pest German Roach Mosquito 6 Seasonal": "bundle",
  "Pest German Roach Rodent 12": "bundle",
  "Pest German Roach Rodent 4": "bundle",
  "Pest German Roach Rodent 6": "bundle",
  "Pest German Roach Rodent Snake 4": "bundle",
  "Pest German Roach Rodent Snake 6": "bundle",
  "Pest German Roach Snake 4": "bundle",
  "Pest German Roach Snake 6": "bundle",
  "Pest Interior 4": "bundle",
  "Pest Interior 6": "bundle",
  "Pest Interior Flea 4": "bundle",
  "Pest Interior Flea 6": "bundle",
  "Pest Interior Flea Mole 4": "bundle",
  "Pest Interior Flea Mosquito 4": "bundle",
  "Pest Interior Flea Mosquito 4 Seasonal": "bundle",
  "Pest Interior Flea Rodent 6": "bundle",
  "Pest Interior German Roach 4": "bundle",
  "Pest Interior German Roach Rodent 4": "bundle",
  "Pest Mole 12": "bundle",
  "Pest Mole 4": "bundle",
  "Pest Mole 6": "bundle",
  "Pest Mole Initial": "exclude",
  "Pest Mole Mosquito 4": "bundle",
  "Pest Mole Mosquito 4 Seasonal": "bundle",
  "Pest Mole Mosquito 6": "bundle",
  "Pest Mole Mosquito 6 Seasonal": "bundle",
  "Pest Mole Mosquito Rodent 6": "bundle",
  "Pest Mole Mosquito Snake 4": "bundle",
  "Pest Mole Mosquito Snake 6": "bundle",
  "Pest Mole Mosquito Snake 6 Seasonal": "bundle",
  "Pest Mole Rodent 4": "bundle",
  "Pest Mole Rodent 6": "bundle",
  "Pest Mole Rodent Snake 6": "bundle",
  "Pest Mole Snake 4": "bundle",
  "Pest Mole Snake 6": "bundle",
  "Pest Mole Snake Rodent 4": "bundle",
  "Pest Mosquito 12": "bundle",
  "Pest Mosquito 3 Seasonal": "bundle",
  "Pest Mosquito 4": "bundle",
  "Pest Mosquito 4 - Spanish": "bundle",
  "Pest Mosquito 4 Seasonal": "bundle",
  "Pest Mosquito 6": "bundle",
  "Pest Mosquito 6 - Spanish": "bundle",
  "Pest Mosquito 6 Seasonal": "bundle",
  "Pest Mosquito 6 Seasonal - Spanish": "bundle",
  "Pest Mosquito Carpenter Bee 4": "bundle",
  "Pest Mosquito Initial": "exclude",
  "Pest Mosquito Rodent 6": "bundle",
  "Pest Mosquito Snake 4": "bundle",
  "Pest Mosquito Snake 4 Seasonal": "bundle",
  "Pest Mosquito Snake 6": "bundle",
  "Pest Mosquito Snake 6 Seasonal": "bundle",
  "Pest Rodent 12": "bundle",
  "Pest Rodent 3": "bundle",
  "Pest Rodent 4": "bundle",
  "Pest Rodent 6": "bundle",
  "Pest Rodent Mole 4": "bundle",
  "Pest Rodent Snake 4": "bundle",
  "Pest Rodent Snake 6": "bundle",
  "Pest Snake 12": "bundle",
  "Pest Snake 4": "bundle",
  "Pest Snake 6": "bundle",
  "Quarterly Service": "bundle",
  "RIDD Package 12": "bundle",
  "RIDD Package 4": "bundle",
  "RIDD Package 4 - Spanish": "bundle",
  "RIDD Package 4 Seasonal": "bundle",
  "RIDD Package 6": "bundle",
  "RIDD Package 6 - Spanish": "bundle",
  "RIDD Package 6 Seasonal": "bundle",
  "RIDD Package Carpenter Bee 12": "bundle",
  "RIDD Package Carpenter Bee 4": "bundle",
  "RIDD Package Carpenter Bee 6": "bundle",
  "RIDD Package Carpenter Bee 6 Seasonal": "bundle",
  "RIDD Package Carpenter Bee German Roach 4": "bundle",
  "RIDD Package Carpenter Bee Mole 4": "bundle",
  "RIDD Package Carpenter Bee Mole 6": "bundle",
  "RIDD Package Carpenter Bee Mole 6 Seasonal": "bundle",
  "RIDD Package Carpenter Bee Snake 12": "bundle",
  "RIDD Package Carpenter Bee Snake 6 Seasonal": "bundle",
  "RIDD Package German Roach 12": "bundle",
  "RIDD Package German Roach 4": "bundle",
  "RIDD Package German Roach 4 Seasonal": "bundle",
  "RIDD Package German Roach 6": "bundle",
  "RIDD Package German Roach 6 Seasonal": "bundle",
  "RIDD Package German Roach Carpenter Bee 6": "bundle",
  "RIDD Package German Roach Interior Flea 4": "bundle",
  "RIDD Package German Roach Interior Flea 6": "bundle",
  "RIDD Package German Roach Mole 4": "bundle",
  "RIDD Package German Roach Mole 6": "bundle",
  "RIDD Package German Roach Mole 6 Seasonal": "bundle",
  "RIDD Package German Roach Snake 12": "bundle",
  "RIDD Package German Roach Snake 4": "bundle",
  "RIDD Package German Roach Snake 6": "bundle",
  "RIDD Package German Roach Snake 6 Seasonal": "bundle",
  "RIDD Package Interior Flea 4": "bundle",
  "RIDD Package Interior Flea 6": "bundle",
  "RIDD Package Interior Flea 6 Seasonal": "bundle",
  "RIDD Package Interior Flea Mole 6": "bundle",
  "RIDD Package Interior Flea Mole 6 Seasonal": "bundle",
  "RIDD Package Interior Flea Snake 6 Seasonal": "bundle",
  "RIDD Package Mole 12": "bundle",
  "RIDD Package Mole 4": "bundle",
  "RIDD Package Mole 6": "bundle",
  "RIDD Package Mole 6 Seasonal": "bundle",
  "RIDD Package Mole Snake 12": "bundle",
  "RIDD Package Mole Snake 4": "bundle",
  "RIDD Package Mole Snake 6": "bundle",
  "RIDD Package Mole Snake 6 Seasonal": "bundle",
  "RIDD Package Snake 12": "bundle",
  "RIDD Package Snake 4": "bundle",
  "RIDD Package Snake 4 Seasonal": "bundle",
  "RIDD Package Snake 6": "bundle",
  "RIDD Package Snake 6 Seasonal": "bundle",
  "RIDD Package Snake Initial": "exclude",
  "Rodent 12": "bundle",
  "Rodent 4": "bundle",
  "Rodent 6": "bundle",
  "Rodent Initial": "exclude",
  "Rodent Snake 4": "bundle",
  "Seasonal Mosquito Treatment": "bundle",
  "Sentricon Florida - Repair & Retreat": "bundle",
  "Sentricon Florida - Retreat": "bundle",
  "Sentricon Georgia - Repair & Retreat": "bundle",
  "Sentricon Georgia - Retreat": "bundle",
  "Sentricon Install": "exclude",
  "Sentricon Install South Carolina": "exclude",
  "Sentricon Michigan - Retreat": "bundle",
  "Sentricon Monitoring SC": "bundle",
  "Sentricon North Carolina - Repair & Retreat": "bundle",
  "Sentricon North Carolina - Retreat": "bundle",
  "Sentricon South Carolina - Repair & Retreat": "bundle",
  "Sentricon South Carolina - Retreat": "bundle",
  "Sentricon Utah - Retreat": "bundle",
  "Sentricon Virginia - Repair & Retreat": "bundle",
  "Sentricon Virginia - Retreat": "bundle",
  "Sentricon Virginia Beach - Retreat": "bundle",
  "Snake 12": "bundle",
  "Snake 4": "bundle",
  "Snake 6": "bundle",
  "Solo Seasonal Mosquito": "bundle",
  "Termite Repair": "exclude"
}$json$::jsonb)
  || jsonb_build_object(
       'typeRules',
       coalesce(app_settings.value->'typeRules', '{}'::jsonb)
       || jsonb_build_object(
            'Sales Rep',
            coalesce(app_settings.value->'typeRules'->'Sales Rep', '{}'::jsonb)
            || jsonb_build_object('bundleMult', to_jsonb(1::numeric))
          )
     );

-- Verify:
-- select key, jsonb_pretty(value) from public.app_settings where key='commission_config';

insert into public.schema_migrations (name) values ('20261006_sales_rep_full_rate.sql') on conflict do nothing;
