#!/usr/bin/env node
// ════════════════════════════════════════════════════════════════════════
// ADD-ON STREAK FIXTURES — pins netlify/lib/add-on-streak.js: how ticket
// items fold into one add-on and how paid invoices advance / lock / break
// the 5-invoice backend streak (COO rules, Sep 2026).
// ════════════════════════════════════════════════════════════════════════
'use strict';
const assert = require('assert');
const { groupTicketItems, streakOf, LOCK_AT } = require('../netlify/lib/add-on-streak.js');
let n = 0; const t = (name, fn) => { fn(); n++; };

// Modelled on the dummy account [68003] Test Dummy10, sub 193894 (Pest 4):
// base $49 + add-on lines credited to Isaac; the add-on charged $54.87 on
// the initial ticket AND on the recurring ticket.
const tickets = {
  '9001': { customerID: '68003', subscriptionID: '193894', officeID: '7', invoiceDate: '2026-09-21', autoGeneratedType: 'initial' },
  '9002': { customerID: '68003', subscriptionID: '193894', officeID: '7', invoiceDate: '2026-09-21', autoGeneratedType: 'regular' },
};
const items = [
  { ticketItemID: '1', ticketID: '9001', description: 'Pest 4', total: '49.00', employeeID: '' },                           // base service — not an add-on
  { ticketItemID: '2', ticketID: '9001', description: 'Rodent Add-On', total: '54.87', employeeID: '10001', dateCreated: '2026-09-21 10:00:00' },
  { ticketItemID: '3', ticketID: '9002', description: 'Rodent Add-On', total: '54.87', employeeID: '10001', dateCreated: '2026-09-21 10:05:00' },
];
const isAddOn = (name) => /add-on/i.test(name);

t('group: initial + recurring charges of the same add-on fold into ONE row', () => {
  const g = groupTicketItems(items, { isAddOn, tickets });
  assert.strictEqual(g.length, 1);
  const a = g[0];
  assert.strictEqual(a.subscription_id, '193894');
  assert.strictEqual(a.customer_id, '68003');
  assert.strictEqual(a.service_name, 'Rodent Add-On');
  assert.strictEqual(a.credited_employee_id, '10001');
  assert.strictEqual(a.added_at, '2026-09-21');
  assert.strictEqual(a.initial_amount, 54.87);
  assert.strictEqual(a.recurring_amount, 54.87);
  assert.strictEqual(a.initial_ticket_id, '9001');
  assert.strictEqual(a.first_recurring_ticket_id, '9002');
  assert.deepStrictEqual(a.item_ids, ['2', '3']);
});
t('group: two different add-ons on one subscription are two rows', () => {
  const g = groupTicketItems([...items, { ticketItemID: '4', ticketID: '9002', description: 'Mosquito Add-On', total: '30', employeeID: '10002', dateCreated: '2026-09-21' }], { isAddOn, tickets });
  assert.deepStrictEqual(g.map(x => x.service_name).sort(), ['Mosquito Add-On', 'Rodent Add-On']);
});

const addOn = { added_at: '2026-09-21', subscription_active: true };
const inv = (id, date, paid, extra) => ({ ticket_id: id, invoice_date: date, paid, paid_at: paid ? date : null, amount: 103.87, has_add_on: true, active: true, ...(extra || {}) });

t('streak: invoices before the add-on date never count', () => {
  const r = streakOf(addOn, [inv('a', '2026-08-01', true), inv('b', '2026-09-21', true)]);
  assert.strictEqual(r.paid, 1); assert.strictEqual(r.status, 'accruing');
});
t('streak: the add-on date itself counts (initial fee paid same day)', () => {
  const r = streakOf(addOn, [inv('a', '2026-09-21', true)]);
  assert.strictEqual(r.paid, 1);
});
t('streak: unpaid invoices wait — they neither count nor break', () => {
  const r = streakOf(addOn, [inv('a', '2026-09-21', true), inv('b', '2026-10-21', false), inv('c', '2026-11-21', true)]);
  assert.strictEqual(r.paid, 2); assert.strictEqual(r.status, 'accruing');
});
t('streak: 5 paid in a row → locked on the 5th', () => {
  const rows = [1, 2, 3, 4, 5, 6].map(i => inv('t' + i, '2026-' + String(8 + i).padStart(2, '0').replace('13', '12') + '-21', true));
  rows[5].invoice_date = '2027-02-21';
  const r = streakOf(addOn, rows);
  assert.strictEqual(r.status, 'locked'); assert.strictEqual(r.paid, LOCK_AT);
  assert.strictEqual(r.qualifying.length, 5);
  assert.strictEqual(r.lockedAt, rows[4].invoice_date);
});
t('streak: an invoice WITHOUT the add-on breaks it, even if paid', () => {
  const r = streakOf(addOn, [inv('a', '2026-09-21', true), inv('b', '2026-10-21', true, { has_add_on: false }), inv('c', '2026-11-21', true)]);
  assert.strictEqual(r.status, 'broken'); assert.strictEqual(r.reason, 'item_removed'); assert.strictEqual(r.paid, 1); assert.strictEqual(r.brokeAt, '2026-10-21');
});
t('streak: unknown item presence (RevHawk has no items yet) counts as present', () => {
  const r = streakOf(addOn, [inv('a', '2026-09-21', true, { has_add_on: null })]);
  assert.strictEqual(r.paid, 1); assert.strictEqual(r.status, 'accruing');
});
t('streak: subscription cancelled before 5 → broken', () => {
  const r = streakOf({ ...addOn, subscription_active: false, subscription_cancelled_at: '2026-11-02' }, [inv('a', '2026-09-21', true), inv('b', '2026-10-21', true)]);
  assert.strictEqual(r.status, 'broken'); assert.strictEqual(r.reason, 'subscription_cancelled'); assert.strictEqual(r.paid, 2); assert.strictEqual(r.brokeAt, '2026-11-02');
});
t('streak: voided (inactive) tickets are ignored', () => {
  const r = streakOf(addOn, [inv('a', '2026-09-21', true, { active: false })]);
  assert.strictEqual(r.paid, 0);
});

console.log('addon-test: ' + n + ' passed');
